import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, Check, X, RotateCw, RefreshCcw } from 'lucide-react';

interface Flashcard {
  q: string;
  a: string;
}

export function FlashcardsViewer({ content, title }: { content: string, title?: string }) {
  let cards: Flashcard[] = [];
  try {
    const clean = content.replace(/```json/g, '').replace(/```/g, '').trim();
    cards = JSON.parse(clean);
  } catch(e) {
    return <div className="p-4 bg-red-500/10 text-red-400 rounded-2xl border border-red-500/20 text-sm">⚠️ Failed to parse flashcards generated by AI.</div>;
  }

  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [results, setResults] = useState<{gotIt: number, missedIt: number}>({gotIt: 0, missedIt: 0});
  const [completed, setCompleted] = useState(false);

  if (!cards.length) return null;

  const currentCard = cards[currentIndex];

  const handleScore = (type: 'got' | 'miss') => {
    setResults(prev => ({ ...prev, [type === 'got' ? 'gotIt' : 'missedIt']: prev[type === 'got' ? 'gotIt' : 'missedIt'] + 1 }));
    setIsFlipped(false);
    setTimeout(() => {
      if (currentIndex < cards.length - 1) {
        setCurrentIndex(prev => prev + 1);
      } else {
        setCompleted(true);
      }
    }, 200);
  };

  const restart = () => {
    setCurrentIndex(0);
    setIsFlipped(false);
    setResults({gotIt: 0, missedIt: 0});
    setCompleted(false);
  };

  if (completed) {
    return (
      <div className="w-full flex flex-col items-center justify-center p-8 bg-gradient-to-br from-[#0f172a] to-[#1e1b4b] rounded-3xl border border-white/10 shadow-2xl min-h-[400px]">
        <div className="w-20 h-20 bg-amber-500/20 text-amber-400 rounded-full flex items-center justify-center mb-6">
          <Check className="w-10 h-10" />
        </div>
        <h2 className="text-3xl font-black text-white mb-2">Deck Completed!</h2>
        <p className="text-white/60 mb-8 font-medium">Here's how you did:</p>
        
        <div className="flex gap-8 mb-10">
          <div className="text-center">
            <div className="text-4xl font-black text-emerald-400 mb-1">{results.gotIt}</div>
            <div className="text-xs uppercase tracking-widest text-emerald-400/70 font-bold">Got It</div>
          </div>
          <div className="text-center">
            <div className="text-4xl font-black text-rose-400 mb-1">{results.missedIt}</div>
            <div className="text-xs uppercase tracking-widest text-rose-400/70 font-bold">Missed It</div>
          </div>
        </div>

        <button 
          onClick={restart}
          className="flex items-center gap-2 bg-white/10 hover:bg-white/20 px-6 py-3 rounded-xl font-bold text-white transition-colors"
        >
          <RefreshCcw className="w-4 h-4" /> Start Over
        </button>
      </div>
    );
  }

  return (
    <div className="w-full flex flex-col items-center p-6 bg-[#020617] rounded-3xl border border-white/5 shadow-2xl relative min-h-[500px]">
      
      {/* Header */}
      <div className="w-full flex justify-between items-center mb-8 px-2">
        <h3 className="text-sm font-bold text-amber-400 uppercase tracking-wider flex items-center gap-2">
          {title || "Flashcards"}
        </h3>
        <div className="text-xs font-bold text-white/40 bg-white/5 px-3 py-1 rounded-full">
          {currentIndex + 1} / {cards.length}
        </div>
      </div>

      {/* Card Container */}
      <div className="flex-1 w-full max-w-2xl relative perspective-[1000px] mb-8 group cursor-pointer" onClick={() => setIsFlipped(!isFlipped)}>
        <div className={`w-full h-full min-h-[300px] absolute inset-0 transition-transform duration-500 transform-style-3d ${isFlipped ? 'rotate-y-180' : ''}`}>
          
          {/* Front */}
          <div className="w-full h-full absolute inset-0 backface-hidden bg-gradient-to-br from-indigo-900 to-purple-900 rounded-[32px] border border-white/10 shadow-2xl flex flex-col items-center justify-center p-10 text-center">
            <span className="absolute top-6 text-[10px] font-black text-white/30 uppercase tracking-[0.2em]">Question</span>
            <p className="text-2xl md:text-3xl font-medium text-white leading-relaxed">{currentCard.q}</p>
            <div className="absolute bottom-6 flex items-center gap-2 text-white/30 text-xs font-bold group-hover:text-white/50 transition-colors">
              <RotateCw className="w-3 h-3" /> Click to flip
            </div>
          </div>

          {/* Back */}
          <div className="w-full h-full absolute inset-0 backface-hidden rotate-y-180 bg-gradient-to-br from-emerald-900 to-teal-900 rounded-[32px] border border-emerald-500/20 shadow-[0_0_50px_rgba(16,185,129,0.15)] flex flex-col items-center justify-center p-10 text-center">
            <span className="absolute top-6 text-[10px] font-black text-emerald-400/50 uppercase tracking-[0.2em]">Answer</span>
            <p className="text-xl md:text-2xl font-medium text-emerald-50 leading-relaxed">{currentCard.a}</p>
          </div>

        </div>
      </div>

      {/* Controls */}
      <div className="flex items-center justify-center gap-4 w-full h-[60px] transition-all duration-300">
        {!isFlipped ? (
          <button 
            onClick={() => setIsFlipped(true)}
            className="bg-white/10 hover:bg-white/20 text-white font-bold py-3.5 px-8 rounded-full transition-all shadow-lg text-sm"
          >
            Reveal Answer
          </button>
        ) : (
          <div className="flex gap-4 animate-in slide-in-from-bottom-4 fade-in duration-300">
            <button 
              onClick={(e) => { e.stopPropagation(); handleScore('miss'); }}
              className="flex items-center gap-2 bg-rose-500/20 hover:bg-rose-500/30 border border-rose-500/30 text-rose-400 font-bold py-3 px-6 rounded-full transition-all text-sm"
            >
              <X className="w-4 h-4" /> Missed it
            </button>
            <button 
              onClick={(e) => { e.stopPropagation(); handleScore('got'); }}
              className="flex items-center gap-2 bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-bold py-3 px-6 rounded-full transition-all shadow-[0_0_20px_rgba(16,185,129,0.3)] text-sm"
            >
              <Check className="w-4 h-4" /> Got it!
            </button>
          </div>
        )}
      </div>

    </div>
  );
}
